name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Copy Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env.dev
        run: |
          echo "NODE_ENV=dev" >> .env.dev
          echo "SERVER_PORT=3000" >> .env.dev
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env.dev
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env.dev
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env.dev
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env.dev
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env.dev
          echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> .env.dev
          echo "JWT_ACCESS_EXPIRES_IN=${{ secrets.JWT_ACCESS_EXPIRES_IN }}" >> .env.dev
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env.dev
          echo "JWT_REFRESH_EXPIRES_IN=${{ secrets.JWT_REFRESH_EXPIRES_IN }}" >> .env.dev

      - name: Install dependencies
        run: npm ci

      - name: Unit test
        run: npm run test

      - name: E2E test
        run: npm run test:e2e

      - name: Build
        run: npm run build --if-present
